### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by complexpotato** [burgerdev/hideip#1]
OS: linux (Debian)

Tried to see the help menu by : python hideip.py -h
Then nothing appears.
Even tried the doctest, and there were lots of failures on your script.

Is it just for me?

**Comment by burgerdev** [comment]
No, that's totally not just for you - thanks for pointing it out. The doctests were outdated, that's where CI would have helped :), fixed that. I also added a list of requirements to the readme and updated the usage description there.

Please try again:

  * make sure to use `python3`
  * the `cryptography` library is required (but from what I see you have that already)
  * entrypoint is `main.py` these days (`python3 main.py -h`)

And btw, cool that you're tried this out and helped fixing it.
